//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JuicySwapper.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.8.1.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string pakPath {
            get {
                return ((string)(this["pakPath"]));
            }
            set {
                this["pakPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public long current_offset {
            get {
                return ((long)(this["current_offset"]));
            }
            set {
                this["current_offset"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int offset_skin_body {
            get {
                return ((int)(this["offset_skin_body"]));
            }
            set {
                this["offset_skin_body"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int offset_skin_head {
            get {
                return ((int)(this["offset_skin_head"]));
            }
            set {
                this["offset_skin_head"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int offset_pick_mesh {
            get {
                return ((int)(this["offset_pick_mesh"]));
            }
            set {
                this["offset_pick_mesh"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int offset_back_mesh {
            get {
                return ((int)(this["offset_back_mesh"]));
            }
            set {
                this["offset_back_mesh"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int offset_emote_mesh {
            get {
                return ((int)(this["offset_emote_mesh"]));
            }
            set {
                this["offset_emote_mesh"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("11000000")]
        public int offset_temp {
            get {
                return ((int)(this["offset_temp"]));
            }
            set {
                this["offset_temp"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool JuicyEAC1Enabled {
            get {
                return ((bool)(this["JuicyEAC1Enabled"]));
            }
            set {
                this["JuicyEAC1Enabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool BlackShieldEnabled {
            get {
                return ((bool)(this["BlackShieldEnabled"]));
            }
            set {
                this["BlackShieldEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public string MusicAct {
            get {
                return ((string)(this["MusicAct"]));
            }
            set {
                this["MusicAct"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Free")]
        public string AccVerify {
            get {
                return ((string)(this["AccVerify"]));
            }
            set {
                this["AccVerify"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Name {
            get {
                return ((string)(this["Name"]));
            }
            set {
                this["Name"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool EliteAgentEnabled {
            get {
                return ((bool)(this["EliteAgentEnabled"]));
            }
            set {
                this["EliteAgentEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string username {
            get {
                return ((string)(this["username"]));
            }
            set {
                this["username"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Password {
            get {
                return ((string)(this["Password"]));
            }
            set {
                this["Password"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool BrenegadeEnabled {
            get {
                return ((bool)(this["BrenegadeEnabled"]));
            }
            set {
                this["BrenegadeEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool GhoulOGEnabled {
            get {
                return ((bool)(this["GhoulOGEnabled"]));
            }
            set {
                this["GhoulOGEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool RednoseEnabled {
            get {
                return ((bool)(this["RednoseEnabled"]));
            }
            set {
                this["RednoseEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool RrenegadeEnabled {
            get {
                return ((bool)(this["RrenegadeEnabled"]));
            }
            set {
                this["RrenegadeEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool GrenegadeEnabled {
            get {
                return ((bool)(this["GrenegadeEnabled"]));
            }
            set {
                this["GrenegadeEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool WildcatBlueEnabled {
            get {
                return ((bool)(this["WildcatBlueEnabled"]));
            }
            set {
                this["WildcatBlueEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool SirenEnabled {
            get {
                return ((bool)(this["SirenEnabled"]));
            }
            set {
                this["SirenEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool TravisEnabled {
            get {
                return ((bool)(this["TravisEnabled"]));
            }
            set {
                this["TravisEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool BrenegadeCEnabled {
            get {
                return ((bool)(this["BrenegadeCEnabled"]));
            }
            set {
                this["BrenegadeCEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool RrenegadeCEnabled {
            get {
                return ((bool)(this["RrenegadeCEnabled"]));
            }
            set {
                this["RrenegadeCEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool FNCSEnabled {
            get {
                return ((bool)(this["FNCSEnabled"]));
            }
            set {
                this["FNCSEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool GrenegadeCEnabled {
            get {
                return ((bool)(this["GrenegadeCEnabled"]));
            }
            set {
                this["GrenegadeCEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool FreemixEnabled {
            get {
                return ((bool)(this["FreemixEnabled"]));
            }
            set {
                this["FreemixEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool SixStringEnabled {
            get {
                return ((bool)(this["SixStringEnabled"]));
            }
            set {
                this["SixStringEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool InsigniaEnabled {
            get {
                return ((bool)(this["InsigniaEnabled"]));
            }
            set {
                this["InsigniaEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool StuddedEnabled {
            get {
                return ((bool)(this["StuddedEnabled"]));
            }
            set {
                this["StuddedEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ScenarioEnabled {
            get {
                return ((bool)(this["ScenarioEnabled"]));
            }
            set {
                this["ScenarioEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool FlossEnabled {
            get {
                return ((bool)(this["FlossEnabled"]));
            }
            set {
                this["FlossEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int offsetBlaze {
            get {
                return ((int)(this["offsetBlaze"]));
            }
            set {
                this["offsetBlaze"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string pak_skin_body {
            get {
                return ((string)(this["pak_skin_body"]));
            }
            set {
                this["pak_skin_body"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string pak_skin_head {
            get {
                return ((string)(this["pak_skin_head"]));
            }
            set {
                this["pak_skin_head"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string pak_pick_mesh {
            get {
                return ((string)(this["pak_pick_mesh"]));
            }
            set {
                this["pak_pick_mesh"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string pak_back_mesh {
            get {
                return ((string)(this["pak_back_mesh"]));
            }
            set {
                this["pak_back_mesh"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string pak_emote_mesh {
            get {
                return ((string)(this["pak_emote_mesh"]));
            }
            set {
                this["pak_emote_mesh"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool TAKEtLEnabled {
            get {
                return ((bool)(this["TAKEtLEnabled"]));
            }
            set {
                this["TAKEtLEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ChickenEnabled {
            get {
                return ((bool)(this["ChickenEnabled"]));
            }
            set {
                this["ChickenEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool BlackShieldDSEnabled {
            get {
                return ((bool)(this["BlackShieldDSEnabled"]));
            }
            set {
                this["BlackShieldDSEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool BlackShieldFSEnabled {
            get {
                return ((bool)(this["BlackShieldFSEnabled"]));
            }
            set {
                this["BlackShieldFSEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool RaidersRevengeEnabled {
            get {
                return ((bool)(this["RaidersRevengeEnabled"]));
            }
            set {
                this["RaidersRevengeEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool StarwandEnabled {
            get {
                return ((bool)(this["StarwandEnabled"]));
            }
            set {
                this["StarwandEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool StarwandRSEnabled {
            get {
                return ((bool)(this["StarwandRSEnabled"]));
            }
            set {
                this["StarwandRSEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool GuandaoEnabled {
            get {
                return ((bool)(this["GuandaoEnabled"]));
            }
            set {
                this["GuandaoEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool LoserfruitEnabled {
            get {
                return ((bool)(this["LoserfruitEnabled"]));
            }
            set {
                this["LoserfruitEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool AxecaliburEnabled {
            get {
                return ((bool)(this["AxecaliburEnabled"]));
            }
            set {
                this["AxecaliburEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool HarleyHitterEnabled {
            get {
                return ((bool)(this["HarleyHitterEnabled"]));
            }
            set {
                this["HarleyHitterEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool JitterbugEnabled {
            get {
                return ((bool)(this["JitterbugEnabled"]));
            }
            set {
                this["JitterbugEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool AerialAssaultTrooperEnabled {
            get {
                return ((bool)(this["AerialAssaultTrooperEnabled"]));
            }
            set {
                this["AerialAssaultTrooperEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool FlossArmWaveEnabled {
            get {
                return ((bool)(this["FlossArmWaveEnabled"]));
            }
            set {
                this["FlossArmWaveEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool WildcatRSEnabled {
            get {
                return ((bool)(this["WildcatRSEnabled"]));
            }
            set {
                this["WildcatRSEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool SpectralSpineEnabled {
            get {
                return ((bool)(this["SpectralSpineEnabled"]));
            }
            set {
                this["SpectralSpineEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ReconSpecialistEnabled {
            get {
                return ((bool)(this["ReconSpecialistEnabled"]));
            }
            set {
                this["ReconSpecialistEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool GalaxyEnabled {
            get {
                return ((bool)(this["GalaxyEnabled"]));
            }
            set {
                this["GalaxyEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool OctaneEnabled {
            get {
                return ((bool)(this["OctaneEnabled"]));
            }
            set {
                this["OctaneEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool SavageEnabled {
            get {
                return ((bool)(this["SavageEnabled"]));
            }
            set {
                this["SavageEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool SaySoEnabled {
            get {
                return ((bool)(this["SaySoEnabled"]));
            }
            set {
                this["SaySoEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool MegumiEnabled {
            get {
                return ((bool)(this["MegumiEnabled"]));
            }
            set {
                this["MegumiEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool YukiEnabled {
            get {
                return ((bool)(this["YukiEnabled"]));
            }
            set {
                this["YukiEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ChigusaEnabled {
            get {
                return ((bool)(this["ChigusaEnabled"]));
            }
            set {
                this["ChigusaEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool MeggEnabled {
            get {
                return ((bool)(this["MeggEnabled"]));
            }
            set {
                this["MeggEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool IsabelleEnabled {
            get {
                return ((bool)(this["IsabelleEnabled"]));
            }
            set {
                this["IsabelleEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool LeaveTheDoorOpenEnabled {
            get {
                return ((bool)(this["LeaveTheDoorOpenEnabled"]));
            }
            set {
                this["LeaveTheDoorOpenEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool RainbowCloverEnabled {
            get {
                return ((bool)(this["RainbowCloverEnabled"]));
            }
            set {
                this["RainbowCloverEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool WildcatBlazeEnabled {
            get {
                return ((bool)(this["WildcatBlazeEnabled"]));
            }
            set {
                this["WildcatBlazeEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool WildcatBlueBlazeEnabled {
            get {
                return ((bool)(this["WildcatBlueBlazeEnabled"]));
            }
            set {
                this["WildcatBlueBlazeEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool WildcatNeoEnabled {
            get {
                return ((bool)(this["WildcatNeoEnabled"]));
            }
            set {
                this["WildcatNeoEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool HarleyQuinnRebirthEnabled {
            get {
                return ((bool)(this["HarleyQuinnRebirthEnabled"]));
            }
            set {
                this["HarleyQuinnRebirthEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool AloyEnabled {
            get {
                return ((bool)(this["AloyEnabled"]));
            }
            set {
                this["AloyEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool AloySpearEnabled {
            get {
                return ((bool)(this["AloySpearEnabled"]));
            }
            set {
                this["AloySpearEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool AloyStyleEnabled {
            get {
                return ((bool)(this["AloyStyleEnabled"]));
            }
            set {
                this["AloyStyleEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool EcoEnabled {
            get {
                return ((bool)(this["EcoEnabled"]));
            }
            set {
                this["EcoEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool GrimeyEnabled {
            get {
                return ((bool)(this["GrimeyEnabled"]));
            }
            set {
                this["GrimeyEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool PrincessFishEnabled {
            get {
                return ((bool)(this["PrincessFishEnabled"]));
            }
            set {
                this["PrincessFishEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string InstallationPath {
            get {
                return ((string)(this["InstallationPath"]));
            }
            set {
                this["InstallationPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool VisionEnabled {
            get {
                return ((bool)(this["VisionEnabled"]));
            }
            set {
                this["VisionEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ACDCEnabled {
            get {
                return ((bool)(this["ACDCEnabled"]));
            }
            set {
                this["ACDCEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool SparkleSpecialistEnabled {
            get {
                return ((bool)(this["SparkleSpecialistEnabled"]));
            }
            set {
                this["SparkleSpecialistEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool GrimeyBlazeEnabled {
            get {
                return ((bool)(this["GrimeyBlazeEnabled"]));
            }
            set {
                this["GrimeyBlazeEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ChunLiEnabled {
            get {
                return ((bool)(this["ChunLiEnabled"]));
            }
            set {
                this["ChunLiEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool IkonikEnabled {
            get {
                return ((bool)(this["IkonikEnabled"]));
            }
            set {
                this["IkonikEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool GrimoreEnabled {
            get {
                return ((bool)(this["GrimoreEnabled"]));
            }
            set {
                this["GrimoreEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool RueEnabled {
            get {
                return ((bool)(this["RueEnabled"]));
            }
            set {
                this["RueEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool SurfwitchEnabled {
            get {
                return ((bool)(this["SurfwitchEnabled"]));
            }
            set {
                this["SurfwitchEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool EchoEnabled {
            get {
                return ((bool)(this["EchoEnabled"]));
            }
            set {
                this["EchoEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool FocusEnabled {
            get {
                return ((bool)(this["FocusEnabled"]));
            }
            set {
                this["FocusEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool LaceEnabled {
            get {
                return ((bool)(this["LaceEnabled"]));
            }
            set {
                this["LaceEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ScourgeEnabled {
            get {
                return ((bool)(this["ScourgeEnabled"]));
            }
            set {
                this["ScourgeEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ChaosAgentEnabled {
            get {
                return ((bool)(this["ChaosAgentEnabled"]));
            }
            set {
                this["ChaosAgentEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool AthleisureAssassinEnabled {
            get {
                return ((bool)(this["AthleisureAssassinEnabled"]));
            }
            set {
                this["AthleisureAssassinEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool VictoriaSaintEnabled {
            get {
                return ((bool)(this["VictoriaSaintEnabled"]));
            }
            set {
                this["VictoriaSaintEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool TropicalZoeyEnabled {
            get {
                return ((bool)(this["TropicalZoeyEnabled"]));
            }
            set {
                this["TropicalZoeyEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool TechLlamaEnabled {
            get {
                return ((bool)(this["TechLlamaEnabled"]));
            }
            set {
                this["TechLlamaEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool HarleyQuinnEnabled {
            get {
                return ((bool)(this["HarleyQuinnEnabled"]));
            }
            set {
                this["HarleyQuinnEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool HushEnabled {
            get {
                return ((bool)(this["HushEnabled"]));
            }
            set {
                this["HushEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ManicEnabled {
            get {
                return ((bool)(this["ManicEnabled"]));
            }
            set {
                this["ManicEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ReysQuarterstaffEnabled {
            get {
                return ((bool)(this["ReysQuarterstaffEnabled"]));
            }
            set {
                this["ReysQuarterstaffEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool CandyAxeEnabled {
            get {
                return ((bool)(this["CandyAxeEnabled"]));
            }
            set {
                this["CandyAxeEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool GalaxyAxeEnabled {
            get {
                return ((bool)(this["GalaxyAxeEnabled"]));
            }
            set {
                this["GalaxyAxeEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool HitItEnabled {
            get {
                return ((bool)(this["HitItEnabled"]));
            }
            set {
                this["HitItEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool MintyEnabled {
            get {
                return ((bool)(this["MintyEnabled"]));
            }
            set {
                this["MintyEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool TigeressEnabled {
            get {
                return ((bool)(this["TigeressEnabled"]));
            }
            set {
                this["TigeressEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool PullUpEnabled {
            get {
                return ((bool)(this["PullUpEnabled"]));
            }
            set {
                this["PullUpEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool CatComicEnabled {
            get {
                return ((bool)(this["CatComicEnabled"]));
            }
            set {
                this["CatComicEnabled"] = value;
            }
        }
    }
}
